# ~/.zshrc
# Last updated: 4/11/15 by Brett Levenson
# Description:
# This file is the main configuration file in zsh
# You can put configuration directives here, or add them to other files and use the `source` command to load them

# User configuration
if [[ ! "$PATH" == *"/usr/local"* ]]; then
	# If we're here, then the PATH var does not yet contain /usr/local, so we add it
	export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:$PATH
fi

# If user does not use ohmyzsh, then we want to load these files
# NOTE: If you'd like to use the global config files even WITH ohmyzsh, just remove the '!' from the beginning of this 'if' statement
ohmyzsh_checker="^.*\.oh-my-zsh"
if [[ ! "$ZSH" =~ $ohmyzsh_checker ]]; then
	# if we're here, then oh my zsh is not installed
	config_files=(".shell_aliases" ".shell_functions" ".shell_variables")
	# load each file in "config_files" in the order they appear in the array
	for file in "${config_files[@]}"; do
		if [ -f ~/"$file" ]; then
			source ~/"$file"
		fi	
	done
fi




